config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  resources :homes, only: [:new, :create, :index]
  get 'home/about' => 'homes#about'
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:new, :create, :index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get "search" => "searches#search"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: params[:book_id])
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: params[:book_id])
    favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
    <span>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    ♥<%= book.favorites.count %>
    <% end %>
    </span>
<% else %>
    <span>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    ♡<%= book.favorites.count %>
    <% end %>
    </span>
<% end %>

app/views/favorites/create.js.erb
$(".favorite-btn_<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$(".favorite-btn_<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");