config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  resources :homes, only: [:new, :create, :index]
  get 'home/about' => 'homes#about'
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:new, :create, :index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get "search" => "searches#search"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  attachment :profile_image

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

 #住所機能
  include JpPrefecture
  jp_prefecture :prefecture_code  #prefecture_codeはuserが持っているカラム

  #postal_codeからprefecture_nameに変換するメソッド
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end


  validates :name,  presence: true
  validates :name,  uniqueness: true
  validates :name, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.new
    @user = current_user
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully!"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    unless params[:id].to_i == current_user.id
    redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

  <div class="col-md-3">
  <h1>User info</h1>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
    <tr>
      <td>name</td>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <td>introduction</td>
      <td><%= user.introduction %></td>
    </tr>
    <tr>
      <td>follows</td>
      <td><%= user.followings.count %></td>
    </tr>
    <tr>
      <td>followers</td>
      <td><%= user.followers.count %></td>
    </tr>
  </tbody>
  </table>
  <div class="row">
  <%= link_to '',edit_user_path(user), class: "col-sm-12 btn btn-outline-secondary btn-block fas fa-user-cog  edit_user_#{user.id}" %>
  </div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error
  <% @user.errors.full_messages.each do |message| %>
  <%= message %>
  <% end %>
<% end %>
<h1>User info</h1>
<%= form_with model:@user, local:true do |f| %>
  <div class="user-name">Name</div>
    <%= f.text_field :name %>
  <div class="user-edit-image">Image</div>
    <%= f.attachment_field :profile_image %>
  <div class="form-body">Introduction</div>
    <%= f.text_area :introduction %><br>
  <div class="upload">
    <%= f.submit " Update User" %>
  </div>
<% end %>

app/views/users/index.html.erb
<%= render 'users/profile', user: @user %>
<<%= render 'books/new', book: @book %>

 <div class="col-md-8 offset-md-1">
   <table class="table">
     <h1>Users</h1>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>

        <% if user != current_user %>
          <% if current_user.following?(user) %>
          <td>
          <%= link_to "フォロー外す", user_relationships_path(user), method: :delete %>
          </td>
          <% else %>
          <td>
          <%= link_to "フォローする", user_relationships_path(user), method: :post %>
          </td>
          <% end %>
        <% else %>
          <td></td>
        <% end %>

        <td><%= link_to 'Show',user_path(user.id) %></td>
        </tr>
        <% end %>
      </tbody>
   </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

  <div class="col-md-3">
  <h1>User info</h1>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
    <tr>
      <td>name</td>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <td>introduction</td>
      <td><%= @user.introduction %></td>
    </tr>
    <tr>
      <td>follows</td>
      <td><%= link_to @user.followings.count,user_followings_path(@user) %></td>
    </tr>
    <tr>
      <td>followers</td>
      <td><%= link_to @user.followers.count,user_followers_path(@user) %></td>
    </tr>
  </tbody>
  </table>
  <% if @user != current_user %>
    <% if current_user.following?(@user) %>
    <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %>
    <% else %>
    <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
    <% end %>
  <% end %>
  <div class="row">
  <%= link_to '',edit_user_path(@user), class: "col-sm-12 btn btn-outline-secondary btn-block fas fa-user-cog  edit_user_#{@user.id}" %>
  </div>

  <<%= render 'books/new', book: @book %>

  <div class="col-md-8 offset-md-1">
    <h1>Books</h1>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
        <td><%= link_to (attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"),user_path(@user) %></td>
        <td><%= link_to book.title,book_path(book) %></td>
        <td><%= book.body %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  </div>
</div>